import type { NextPage } from 'next';
import Head from 'next/head';
import Masthead from '../components/Masthead';
import About from '../components/About';
import Skills from '../components/Skills';
import Works from '../components/Works';
import TrustedBy from '../components/TrustedBy';
import ContactUs from '../components/ContactUs';
import Testimonials from '../components/Testimonials';
import Footer from '../components/Footer';
import useSWR from 'swr';

const fetcher = (input: any, init?: any) =>
  fetch(input, init).then((res) => res.json());

const Home: NextPage = () => {
  const { data } = useSWR('/api/stats', fetcher);

  return (
    <div>
      <Head>
        <title>Waves</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Masthead />
      <About />
      <Skills commits={data?.commits} />
      <Works />
      <TrustedBy />
      <Testimonials />
      <ContactUs />
      <Footer />
    </div>
  );
};

export default Home;
