import type { NextPage } from 'next';
import Head from 'next/head';
import Masthead from '../components/Masthead';
import About from '../components/About';
import Skills from '../components/Skills';
import Works from '../components/Works';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Waves</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Masthead />
      <About />
      <Skills />
      <Works />
    </div>
  );
};

export default Home;
